### ISSUE TITLE
How to add the lazy.nvim table for lazy loading

### ISSUE THREAD

**Issue by voyeg3r** [backdround/improved-ft.nvim#4]
Currently there is no informatio on how to lazy load the plugin. Because many people need to improve their startup time.

**Comment by voyeg3r** [comment]
I figured out how to do it. But would be great to add in the README

```
return {
  "backdround/improved-ft.nvim",
  opts = {
    use_default_mappings = true,
  },
  keys = {
    { 'f', 'f' ,{ desc = 'Jump to char'}},
    { 'F', 'F' ,{ desc = 'Jump before char'}},
    { 't', 't' ,{ desc = 'Jump forward to char'}},
    { 'T', 'T' ,{ desc = 'Jump backward to char'}},
    { ';', ';' ,{ desc = 'Repear jump forward'}},
    { ',', ',' ,{ desc = 'Repeat jump backward '}},
  }
}
```

**Comment by voyeg3r** [comment]
The only problem seems to be the insert mode jumps

**Comment by backdround** [comment]
> I figured out how to do it. But would be great to add in the README

I'm not sure that this should be in the README because there is nothing specific to the plugin barring probably default mappings.

**Comment by backdround** [comment]
> The only problem seems to be the insert mode jumps

There are no default mappings in insert mode. All that one has to do is add his own mappings in the `keys` field.

Something like:
```lua
keys = {
  { "<M-f>", mode = "i", desc = "Jump forward to char" },
  { "<M-F>", mode = "i", desc = "Jump backward to char" },
  ...
}
```
